feature:
  - name : ~

models:
  gin:
    - parameterName: num_layers
      type: FIXED
      value: 6
    
    - parameterName: hidden
      type: FIXED
      value: [32,32,32,32,32]
    
    - parameterName: dropout
      type: FIXED
      value: 0.5
    
    - parameterName: act
      type: FIXED
      value: relu

    - parameterName: eps
      type: FIXED
      value: True

    - parameterName: mlp_layers
      type: FIXED
      value: 2

trainer:
  - parameterName: max_epoch
    type: FIXED
    value: 350
  
  - parameterName: early_stopping_round
    type: FIXED
    value: 10

  - parameterName: lr
    type: FIXED
    value: 0.01
  
  - parameterName: weight_decay
    type: FIXED
    value: 0

  - parameterName: batch_size
    type: FIXED
    value: 32

# hidden tuned in {16,32} for bioinformatics,64 for social
# batch tuned in {32,128}
# dropout tuned in {0,0.5}

# weight decay （0.5 every 50 epochs)

# max epoch 350 
# early stop epochs (run to end?), best for 10 folds

hpo:
  name: random
  max_evals: 1

ensemble:
  name: ~