ensemble:
  name: null
feature:
- name: PYGNormalizeFeatures
hpo:
  max_evals: 10
  name: random
models:
- hp_space:
  - parameterName: num_layers
    type: FIXED
    value: 5
  - parameterName: hidden
    type: CATEGORICAL_LIST
    cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 4
    feasiblePoints:
    - 128
    - 256
    - 512
  - maxValue: 0.8
    minValue: 0.2
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  - parameterName: add_self_loops
    type: FIXED
    value: 0
  - parameterName: normalize
    type: FIXED
    value: 0
  name: gcn
trainer:
  name: NodeClassificationLayerDependentImportanceSamplingTrainer
  hp_space:
  - parameterName: sampled_node_sizes
    type: CATEGORICAL_LIST
    length: 5
    feasiblePoints:
    - 128
    - 256
    - 512
    - 1024
    cutFunc: lambda x:x[0]
    cutPara:
    - num_layers
  - maxValue: 128
    minValue: 64
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 16
    minValue: 8
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - parameterName: training_batch_size
    type: FIXED
    value: 1024
  - parameterName: predicting_batch_size
    type: FIXED
    value: 1024
  - parameterName: predicting_sampler_num_workers
    type: FIXED
    value: 0
  - maxValue: 0.05
    minValue: 0.01
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.0005
    minValue: 0.0001
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE
