ensemble:
  name: voting
  size: 2
feature:
- name: PYGNormalizeFeatures
- name: pagerank
hpo:
  max_evals: 10
  name: anneal
models:
- hp_space:
  - feasiblePoints: 2,3,4
    parameterName: num_layers
    type: DISCRETE
  - feasiblePoints: 4,8,16
    parameterName: heads
    type: DISCRETE
  - cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 3
    maxValue:
    - 64
    - 64
    - 64
    minValue:
    - 8
    - 8
    - 8
    numericalType: INTEGER
    parameterName: hidden
    scalingType: LOG
    type: NUMERICAL_LIST
  - maxValue: 0.9
    minValue: 0.1
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  name: gat
trainer:
  hp_space:
  - maxValue: 300
    minValue: 10
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 30
    minValue: 10
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.1
    minValue: 0.0001
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.005
    minValue: 5.0e-05
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE
