ensemble:
  name: null
feature:
- name: PYGNormalizeFeatures
hpo:
  max_evals: 10
  name: random
models:
- hp_space:
  - feasiblePoints:
    - 0
    parameterName: add_self_loops,
    type: CATEGORICAL,
  - feasiblePoints: 5,5
    parameterName: num_layers
    type: DISCRETE
  - cutFunc: lambda x:x[0] - 1
    cutPara:
    - num_layers
    length: 4
    maxValue: 256
    minValue: 64
    numericalType: INTEGER
    parameterName: hidden
    scalingType: LOG
    type: NUMERICAL_LIST
  - maxValue: 0.8
    minValue: 0.2
    parameterName: dropout
    scalingType: LINEAR
    type: DOUBLE
  - feasiblePoints:
    - leaky_relu
    - relu
    - elu
    - tanh
    parameterName: act
    type: CATEGORICAL
  name: gcn
trainer:
  name: NodeClassificationLayerDependentImportanceSamplingTrainer
  hp_space:
  - feasiblePoints: 128,256,512
    parameterName: sampled_node_size_budget
    type: DISCRETE
  - maxValue: 300
    minValue: 100
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 30
    minValue: 10
    parameterName: early_stopping_round
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 0.05
    minValue: 0.01
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0.0005
    minValue: 0.0001
    parameterName: weight_decay
    scalingType: LOG
    type: DOUBLE
