ensemble:
  name: null
feature:
- name: PYGNormalizeFeatures
hpo:
  max_evals: 20
  name: random
models:
- hp_space:
  - feasiblePoints: [5]
    parameterName: num_layers
    type: CATEGORICAL
  - parameterName: hidden
    type: CATEGORICAL_LIST
    cutFunc: lambda x:x[0] - 1
    cutPara: [num_layers]
    length: 4
    feasiblePoints: [256]
  - cutFunc: lambda x:x[0]
    cutPara: [num_layers]
    length: 5
    maxValue: [0.2, 0.2, 0.2, 0.2, 0.6]
    minValue: [0.2, 0.2, 0.2, 0.2, 0.6]
    numericalType: DOUBLE
    parameterName: dropout
    scalingType: LINEAR
    type: NUMERICAL_LIST
  - feasiblePoints: [elu]
    parameterName: act
    type: CATEGORICAL
  - parameterName: add_self_loops
    type: FIXED
    value: 0
  - parameterName: normalize
    type: FIXED
    value: 0
  name: gcn
trainer:
  name: NodeClassificationLayerDependentImportanceSamplingTrainer
  hp_space:
  - parameterName: sampled_node_sizes
    type: CATEGORICAL_LIST
    length: 5
    feasiblePoints: [512]
    cutFunc: lambda x:x[0]
    cutPara: [num_layers]
  - maxValue: 128
    minValue: 64
    parameterName: max_epoch
    scalingType: LINEAR
    type: INTEGER
  - maxValue: 12
    minValue: 6
    parameterName: early_stopping_round
    scalingType: LOG
    type: INTEGER
  - parameterName: training_batch_size
    type: FIXED
    value: 512
  - parameterName: predicting_batch_size
    type: FIXED
    value: 1024
  - parameterName: training_sampler_num_workers
    type: FIXED
    value: 0
  - parameterName: predicting_sampler_num_workers
    type: FIXED
    value: 0
  - maxValue: 0.001
    minValue: 0.0005
    parameterName: lr
    scalingType: LOG
    type: DOUBLE
  - maxValue: 0
    minValue: 0
    parameterName: weight_decay
    scalingType: LINEAR
    type: DOUBLE
